"""empty message

Revision ID: 1af63fa3cc07
Revises: 3b4d7d6853b1
Create Date: 2020-08-09 16:00:39.825065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af63fa3cc07'
down_revision = '3b4d7d6853b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productid', sa.String(), nullable=False))
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('products', 'productid')
    # ### end Alembic commands ###
